DROP TABLE IF EXISTS `USER`;
CREATE TABLE IF NOT EXISTS `USER`
(
	`ID` INT(9) PRIMARY KEY AUTO_INCREMENT NOT NULL,
	`USERNAME` VARCHAR(16) NOT NULL,
	`HASHED_PASSWORD` CHAR(32) NOT NULL,
	`EMAIL` VARCHAR(48) NOT NULL,
	`NAME` VARCHAR(60) NOT NULL,
	`ACCESS_LEVEL` TINYINT(2) NOT NULL DEFAULT 0,
	`IS_BLOCKED` TINYINT(2) NOT NULL DEFAULT 1
) ENGINE=MyISAM;


DROP TABLE IF EXISTS `PROBLEM`;
CREATE TABLE IF NOT EXISTS `PROBLEM`
(
	`ID` INT(9) PRIMARY KEY AUTO_INCREMENT NOT NULL,
	`PROBLEMNAME` VARCHAR(48) NOT NULL,
	`PROBLEMTYPE` TINYINT(2) NOT NULL DEFAULT 0
) ENGINE=MyISAM;

DROP TABLE IF EXISTS `SUBMISSION`;
CREATE TABLE IF NOT EXISTS `SUBMISSION`
(
	`ID` INT(9) PRIMARY KEY AUTO_INCREMENT NOT NULL,
	`PROBLEMID` INT(9) NOT NULL,
	`USEDID` INT(9) NOT NULL,
	`LANGUAGE` VARCHAR(10) NOT NULL,
	`STATUS` SMALLINT(5) NOT NULL,
	`POINTS` SMALLINT(8) NOT NULL,
	`TIME` BIGINT NOT NULL,
	`MEMORY` BIGINT NOT NULL,
	`DATE` DATETIME NOT NULL
) ENGINE=MyISAM;
